# Generated by Django 5.0 on 2024-03-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0011_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dailyplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyplan_day', models.CharField(max_length=20)),
                ('dailyplan_file', models.FileField(upload_to='Dailyplan file/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_amount', models.CharField(max_length=20)),
                ('subscription_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trainig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_duration', models.CharField(max_length=20)),
                ('training_details', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_event')),
            ],
        ),
    ]
