# Generated by Django 5.0 on 2024-03-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_delete_tbl_dailyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dailyplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyPlan_day', models.CharField(max_length=20)),
                ('dailyplan_wcount', models.CharField(max_length=20)),
                ('taining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.tbl_trainig')),
            ],
        ),
    ]
