# Generated by Django 5.0 on 2024-03-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0003_tbl_dailyplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_trainig',
            name='event',
        ),
        migrations.DeleteModel(
            name='tbl_dailyplan',
        ),
        migrations.DeleteModel(
            name='tbl_trainig',
        ),
    ]
