# Generated by Django 5.0 on 2024-03-16 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_admin'),
        ('Coach', '0004_remove_tbl_trainig_event_delete_tbl_dailyplan_and_more'),
        ('Guest', '0010_tbl_coach_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_trainig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_duration', models.CharField(max_length=20)),
                ('training_details', models.CharField(max_length=500)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_coach')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_event')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_dailyplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyPlan_day', models.CharField(max_length=20)),
                ('dailyplan_wcount', models.CharField(max_length=20)),
                ('taining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.tbl_trainig')),
            ],
        ),
    ]
