# Generated by Django 5.0 on 2024-03-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0005_tbl_trainig_tbl_dailyplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_dailyplan',
            old_name='dailyPlan_day',
            new_name='dailyplan_day',
        ),
    ]
