# Generated by Django 5.0 on 2024-03-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0007_rename_taining_tbl_dailyplan_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=20)),
                ('workout_discription', models.CharField(max_length=500)),
                ('workout_file', models.FileField(upload_to='workout-file/')),
                ('dailyplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.tbl_dailyplan')),
            ],
        ),
    ]
