# Generated by Django 5.0 on 2024-04-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0008_tbl_workout'),
        ('Guest', '0013_tbl_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subscription',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_coach'),
        ),
    ]
