# Generated by Django 5.0 on 2023-12-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_category',
            old_name='catgory_name',
            new_name='category_name',
        ),
    ]
