# Generated by Django 5.0 on 2024-02-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
    ]
