# Generated by Django 5.0 on 2024-02-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0011_tbl_admin'),
        ('Guest', '0007_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.CharField(max_length=20)),
                ('product_photo', models.FileField(upload_to='ProductPhoto/')),
                ('coach_licence', models.FileField(upload_to='Coachlic')),
                ('coach_password', models.CharField(max_length=20)),
                ('coach_vstatus', models.CharField(default='0', max_length=1, null=True)),
                ('scategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_scategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
    ]
