# Generated by Django 5.0 on 2024-02-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='coach_licence',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='coach_password',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='coach_vstatus',
        ),
    ]
