# Generated by Django 5.0 on 2024-02-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_tbl_product_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_product_gallery',
            old_name='product_id',
            new_name='product',
        ),
    ]
