# Generated by Django 5.0 on 2024-04-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_rename_product_id_tbl_product_gallery_product'),
        ('User', '0010_delete_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product_gallery',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_product_gallery',
        ),
    ]
