# Generated by Django 5.0 on 2024-02-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_coach',
            name='district',
        ),
    ]
