# Generated by Django 5.0 on 2024-02-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_tbl_place_district_delete_tbl_district'),
        ('Guest', '0002_remove_tbl_coach_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_coach',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_state'),
        ),
    ]
