# Generated by Django 5.0 on 2024-02-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_district_tbl_place'),
        ('Guest', '0003_alter_tbl_coach_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_coach',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
    ]
