# Generated by Django 5.0 on 2024-02-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_coach_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_coach',
            name='coach_vstatus',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
