# Generated by Django 5.0 on 2024-02-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_admin'),
        ('Guest', '0006_tbl_coach_coach_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_email', models.CharField(max_length=20)),
                ('shop_contact', models.CharField(max_length=20)),
                ('shop_address', models.CharField(max_length=100)),
                ('shop_photo', models.FileField(upload_to='Shopphoto/')),
                ('shop_proof', models.FileField(upload_to='Shopproof/')),
                ('shop_password', models.CharField(max_length=20)),
                ('shop_vstatus', models.CharField(default='0', max_length=1)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
