# Generated by Django 5.0 on 2024-02-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_vstatus',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
