# Generated by Django 5.0 on 2024-04-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_coach_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('coach_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_from', to='Guest.tbl_coach')),
                ('coach_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_to', to='Guest.tbl_coach')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
