# Generated by Django 5.0 on 2024-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_chat_coach_from_alter_tbl_chat_coach_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queries_name', models.CharField(max_length=20)),
                ('queries_email', models.CharField(max_length=20)),
                ('queries_message', models.CharField(max_length=500)),
            ],
        ),
    ]
