# Generated by Django 5.0 on 2024-02-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_deliverydate',
            field=models.DateField(null=True),
        ),
    ]
