# Generated by Django 5.0 on 2024-04-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shopcomplaint',
        ),
    ]
