# Generated by Django 5.0 on 2024-04-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_delete_tbl_shopcomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
