# Generated by Django 5.0 on 2024-04-12 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0008_tbl_workout'),
        ('Guest', '0013_tbl_queries'),
        ('User', '0011_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.tbl_workout')),
            ],
        ),
    ]
