# Generated by Django 5.0 on 2024-04-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0009_tbl_subscription_coach'),
        ('Guest', '0013_tbl_queries'),
        ('User', '0012_tbl_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.tbl_subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
